### ISSUE TITLE
Colocar app em produção

### ISSUE THREAD

**Issue by gabrielbdornas** [meadapt/mostrando-raiane-quiz-mkdocs-meadapt#3]

**Comment by raianecardoso** [comment]
Primeiro Deploy falhou. No log do servidor no render, aparece a seguinte mensagem: 

`
[2024-11-04 20:31:18 -0300] [97] [INFO] ASGI 'lifespan' protocol appears unsupported.
[2024-11-04 20:31:18 -0300] [97] [INFO] Application startup complete.
127.0.0.1:52412 - "HEAD / HTTP/1.1" 404
==> Your service is live 🎉
34.82.24.137:0 - "GET / HTTP/1.1" 404`

ver: https://stackoverflow.com/questions/61300314/django-uvicorn

**Comment by gabrielbdornas** [comment]
@raianecardoso, vou fechar o Issue, pois conseguimos finalizar a questão. Se for preciso reabrimos.
