### ISSUE TITLE
Erro 500 ao tentar realizar login

### ISSUE THREAD

**Issue by raianecardoso** [meadapt/mostrando-raiane-quiz-mkdocs-meadapt#5]
@gabrielbdornas, 

- Eu identifiquei que a [página inicial](https://aura-mg.onrender.com/admin/login/?next=/admin/)  da AURA estava carregando, mas ao tentar fazer login, este falhava, retornando a mensagem de erro  `Server Error (500) erro` , como comentei com você. Desconfiei que o mesmo poderia ocorrer no nosso CRM, então tentei acessar constatei o mesmo erro. 
- Depois de algumas pesquisas, identifiquei que o erro ocorre por uma falha na conexão com a base de dados. Tudo documentado neste [issue](https://github.com/automatiza-mg/aura/issues/29). Basicamente, por inatividade, o Supabase desativa o projeto e, por conseguinte, o Render não consegue conectar e logar. 
- Para resolver, basta reativar o projeto no Supabase.
____

Estou relatando nesse issue, para 
- registrar e para que saibamos o que fazer caso este erro ocorra; e
- para discutimos se não seria o caso de pagarmos o Supabase, para que os alunos não enfrentem essa situação. Ou, teríamos que criar uma rotina se ativar o projeto. O que você acha?

**Comment by gabrielbdornas** [comment]
See #6 

[Este commit visa resolver este problema](https://github.com/meadapt/crm-meadapt/commit/f74cc9cc72c02f44baf1f2d2173955df4012ad35).
