### ISSUE TITLE
Criar actions para não deixar supabase ficar inativo

### ISSUE THREAD

**Issue by adm-meadapt** [meadapt/mostrando-raiane-quiz-mkdocs-meadapt#6]
@raianecardoso, isso pode ser um vídeo nosso.
Também inclua aqui o Issue que você documentou esta situação para a Aura.

**Comment by raianecardoso** [comment]
Já está registrado aqui #5. 
Sobre o vídeo, coloquei em um issue o nosso [Mini curso de Git avançado](https://github.com/meadapt/planner/issues/35#issue-2716164396)

**Comment by gabrielbdornas** [comment]
[Este vídeo](https://www.youtube.com/watch?v=_1sJlKGTQmM) mostrou no minuto 5:09 qual é a url e a senha.

Encontrei nas opções de conexão:

![image](https://github.com/user-attachments/assets/a47f1694-61d2-490d-913e-3b3720328c58)

![image](https://github.com/user-attachments/assets/650c47ca-755c-4391-8837-791451253c8e)

[Documentação Client Python](https://supabase.com/docs/reference/python/introduction).

**Comment by gabrielbdornas** [comment]
@raianecardoso, favor monitorar. Feito [neste commit](https://github.com/meadapt/mostrando-raiane-quiz-mkdocs-meadapt/commit/f74cc9cc72c02f44baf1f2d2173955df4012ad35).
